name:                easy-security
version:             0.1.0.0
github:              "githubuser/easy-security"
license:             BSD3
author:              "Vlad/Alex"
maintainer:          "otto.muller.general@gmail.com"
copyright:           "ottoMuller"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/easy-security#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  easy-security-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - easy-security

tests:
  easy-security-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - easy-security
